spring.application.name=Student_Management_System

spring.datasource.url=jdbc:mysql://localhost:3306/SpringBoot_SMS
spring.datasource.username=root
spring.datasource.password=

# This is the direct Hibernate property.
# It bypasses Spring Boot?s shortcut and sets Hibernate configuration explicitly.
# Equivalent to putting this in hibernate.cfg.xml if you were configuring Hibernate manually.
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# You can use any of the two depending on what you're trying to achieve
# This is a Spring Boot?specific shortcut property.
# It tells Spring Boot which Hibernate dialect to use.
# Internally, Spring Boot sets Hibernate?s property hibernate.dialect for you.
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.org.hibernate.sql = DEBUG

